/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projetocontinuada1;

import javax.swing.GroupLayout;

/**
 *
 * @author nina-
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCpu = new javax.swing.JLabel();
        barCpu = new javax.swing.JProgressBar();
        lbDisco = new javax.swing.JLabel();
        lbMemoria = new javax.swing.JLabel();
        barDisco = new javax.swing.JProgressBar();
        barMemoria = new javax.swing.JProgressBar();
        btLeitura = new javax.swing.JButton();
        lbMaxCpu = new javax.swing.JLabel();
        lbMaxDisco = new javax.swing.JLabel();
        lbMaxMem = new javax.swing.JLabel();
        lbDadocpu = new javax.swing.JLabel();
        lbDadodisco = new javax.swing.JLabel();
        lbDadomemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 255));

        lbCpu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbCpu.setForeground(new java.awt.Color(135, 92, 222));
        lbCpu.setText("CPU");

        barCpu.setBackground(new java.awt.Color(255, 255, 255));
        barCpu.setForeground(new java.awt.Color(0, 0, 0));
        barCpu.setStringPainted(true);

        lbDisco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDisco.setForeground(new java.awt.Color(135, 92, 222));
        lbDisco.setText("Disco");

        lbMemoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbMemoria.setForeground(new java.awt.Color(135, 92, 222));
        lbMemoria.setText("Memória");

        barDisco.setForeground(new java.awt.Color(0, 0, 0));
        barDisco.setStringPainted(true);

        barMemoria.setForeground(new java.awt.Color(0, 0, 0));
        barMemoria.setStringPainted(true);

        btLeitura.setBackground(new java.awt.Color(153, 102, 255));
        btLeitura.setText("Fazer leitura dos dados");
        btLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLeituraActionPerformed(evt);
            }
        });

        lbMaxCpu.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbMaxCpu.setText("2.30GHz");

        lbMaxDisco.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbMaxDisco.setText("129GB");

        lbMaxMem.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbMaxMem.setText("8.0GB");

        lbDadocpu.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbDadocpu.setText("Dados de CPU");
        lbDadocpu.setMaximumSize(new java.awt.Dimension(80, 15));

        lbDadodisco.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbDadodisco.setText("Dados de Disco");

        lbDadomemoria.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbDadomemoria.setText("Dados de Memória");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMaxDisco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDisco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbMemoria)
                    .addComponent(lbMaxMem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(barMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDadodisco, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDadocpu, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btLeitura)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDadomemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxCpu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDadocpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(barCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbDisco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMaxDisco)
                        .addGap(47, 47, 47)
                        .addComponent(lbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbDadodisco)
                        .addGap(18, 18, 18)
                        .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDadomemoria)
                        .addGap(18, 18, 18)
                        .addComponent(barMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addComponent(btLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLeituraActionPerformed
       
        //CPU
        Double cpu = Math.random()*2.31;
        Integer cpu_inteiro = cpu.intValue();
        barCpu.setValue(cpu_inteiro);
        barCpu.setMaximum(2);
        barCpu.setMinimum(0);
        String cpuString = cpu.toString();
        lbDadocpu.setText(cpuString);
        
        //Disco
        Double disco = Math.random()*129.1;
        Integer disco_inteiro = disco.intValue();
        barDisco.setValue(disco_inteiro);
        barDisco.setMaximum(128);
        barDisco.setMinimum(0);
        String discoString = disco.toString();
        lbDadodisco.setText(discoString);
        
        //Memória
        Double memoria = Math.random()*8.1;
        Integer memoria_inteiro = memoria.intValue();
        barMemoria.setValue(memoria_inteiro);
        barMemoria.setMaximum(7);
        barMemoria.setMinimum(0);
        String memoriaString = memoria.toString();
        lbDadomemoria.setText(memoriaString);

        
    }//GEN-LAST:event_btLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCpu;
    private javax.swing.JProgressBar barDisco;
    private javax.swing.JProgressBar barMemoria;
    private javax.swing.JButton btLeitura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCpu;
    private javax.swing.JLabel lbDadocpu;
    private javax.swing.JLabel lbDadodisco;
    private javax.swing.JLabel lbDadomemoria;
    private javax.swing.JLabel lbDisco;
    private javax.swing.JLabel lbMaxCpu;
    private javax.swing.JLabel lbMaxDisco;
    private javax.swing.JLabel lbMaxMem;
    private javax.swing.JLabel lbMemoria;
    // End of variables declaration//GEN-END:variables
}
